//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCA_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produkt()
        {
            this.EndOfLifeDatas = new HashSet<EndOfLifeData>();
            this.ProduktRohstoffUmweltindikators = new HashSet<ProduktRohstoffUmweltindikator>();
            this.Rohstoffs = new HashSet<Rohstoff>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Menge { get; set; }
        public Nullable<double> Nutzungsdauer_in_Jahre { get; set; }
        public Nullable<double> Gesamtgewicht { get; set; }
        public System.DateTime DateOfCreation { get; set; }
        public System.DateTime DateOfChanging { get; set; }
        public string CreatedBy { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<int> Typ_Id { get; set; }
        public Nullable<decimal> Produktionsmittelkosten { get; set; }
        public Nullable<double> Energieverbrauch_in_GJ { get; set; }
        public Nullable<double> CO2_Ausstoss_t_a { get; set; }
        public Nullable<double> Energiekosten_pro_GJ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EndOfLifeData> EndOfLifeDatas { get; set; }
        public virtual ProduktTyp ProduktTyp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProduktRohstoffUmweltindikator> ProduktRohstoffUmweltindikators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rohstoff> Rohstoffs { get; set; }
    }
}
