//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCA_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Umweltindikatorwert
    {
        public int Id { get; set; }
        public int Umweltindikator_Id { get; set; }
        public Nullable<int> Wert { get; set; }
        public Nullable<int> Rohstoff_Id { get; set; }
    
        public virtual Rohstoff Rohstoff { get; set; }
        public virtual Umweltindikator Umweltindikator { get; set; }
    }
}
